services:
  eventscraper:
    container_name: eventsc
    build: .
    develop:
      watch:
        - action: sync
          path: calendar_event_engine
          target: /app/calendar_event_engine
    security_opt:
      - no-new-privileges:true
    env_file: docker.env
    networks:
        - cteventscraper

networks:
    cteventscraper:
